### ISSUE TITLE
Test Key Notifications Issues

### ISSUE THREAD

**Issue by yasanglass** [sadiqrazasyed/wallpaperboard-enhanced#15]
there is no new commit about notification ads or anything from you, have you silently added that feature or something? i dont want to use notification ads in my app because obviously users hate it.

**Comment by yasanglass** [comment]
in build.gradle there is a new code that links the project to onesignal. so yeah basically if no one notices to change it we get ads from you. nice.

`defaultConfig {
        manifestPlaceholders = [manifestApplicationId: "${applicationId}",
                                onesignal_app_id: "068baede-1a04-432c-b8c4-6fc59bc84500",
                                onesignal_google_project_number: "745634907655"]
    }`

**Comment by genzcodersz** [comment]
I was testing the library in my desktop with notification ADS. Why are you still using the key provided in the sample project? Please generate a key for your app itself. Sample key is for testing purposes only.

Edit: I'm basically working on fixing the library and making it compatible with AS 3.2.0 with banner ADS as well. So there will be furthermore testings in future. I suggest you change the key.

**Comment by yasanglass** [comment]
i just removed changed the strings to empty strings. it should work right? im now trying to build my apps on AS 3.0. still getting some errors tho.

**Comment by genzcodersz** [comment]
Don't keep it empty as that will result in compiling issues. This was the reason why I generated a dummy key. Follow the steps I've written in README on how to get a key for yourself. Regarding the errors, I'll give you a quick fix soon till I update the library itself.

**Comment by yasanglass** [comment]
ive done that now but im still getting this:
(sample app)


Error:FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  warn: removing resource com.yasang.amoledmnml.xfree:string/about_dashboard_dev_github_title without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/about_dashboard_dev_google_plus_title without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/menu_wallpaper_settings without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/pref_others_colored_wallpaper_card without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/pref_wallpaper_location_desc without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_apply_crop without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_download_cancelled without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_download_exist without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_download_exist_new without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_download_exist_replace without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_downloaded without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_new_added without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_settings_crop without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_settings_crop_desc without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_settings_lockscreen without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_settings_lockscreen_desc without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_settings_lockscreen_not_available without required default value.
  C:\Users\Yasan\Documents\GitHub\AMOLED-mnml-X\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:564: error: resource android:attr/fontVariationSettings not found.
  C:\Users\Yasan\Documents\GitHub\AMOLED-mnml-X\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:565: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
  
  Command: C:\Users\Yasan\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.0-4818971-windows.jar\efaaceae4460bdb9bb27b6dba3f17756\aapt2-3.2.0-4818971-windows\aapt2.exe link -I\
          C:\Users\Yasan\AppData\Local\Android\Sdk\platforms\android-26\android.jar\
          --manifest\
          C:\Users\Yasan\Documents\GitHub\AMOLED-mnml-X\app\build\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          C:\Users\Yasan\Documents\GitHub\AMOLED-mnml-X\app\build\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @C:\Users\Yasan\Documents\GitHub\AMOLED-mnml-X\app\build\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          C:\Users\Yasan\Documents\GitHub\AMOLED-mnml-X\app\build\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          com.yasang.amoledmnml.xfree\
          -0\
          apk\
          --output-text-symbols\
          C:\Users\Yasan\Documents\GitHub\AMOLED-mnml-X\app\build\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.0-4818971-windows Daemon #0
  Output:  warn: removing resource com.yasang.amoledmnml.xfree:string/about_dashboard_dev_github_title without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/about_dashboard_dev_google_plus_title without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/menu_wallpaper_settings without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/pref_others_colored_wallpaper_card without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/pref_wallpaper_location_desc without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_apply_crop without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_download_cancelled without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_download_exist without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_download_exist_new without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_download_exist_replace without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_downloaded without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_new_added without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_settings_crop without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_settings_crop_desc without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_settings_lockscreen without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_settings_lockscreen_desc without required default value.
  warn: removing resource com.yasang.amoledmnml.xfree:string/wallpaper_settings_lockscreen_not_available without required default value.
  C:\Users\Yasan\.gradle\caches\transforms-1\files-1.1\design-27.1.0.aar\03df6173ed25ba82360183406c6f7b52\res\values\values.xml:96:5-202: AAPT: error: resource android:attr/fontVariationSettings not found.
      
  C:\Users\Yasan\.gradle\caches\transforms-1\files-1.1\design-27.1.0.aar\03df6173ed25ba82360183406c6f7b52\res\values\values.xml:96:5-202: AAPT: error: resource android:attr/ttcIndex not found.
      
  error: failed linking references.
  Command: C:\Users\Yasan\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.0-4818971-windows.jar\efaaceae4460bdb9bb27b6dba3f17756\aapt2-3.2.0-4818971-windows\aapt2.exe link -I\
          C:\Users\Yasan\AppData\Local\Android\Sdk\platforms\android-26\android.jar\
          --manifest\
          C:\Users\Yasan\Documents\GitHub\AMOLED-mnml-X\app\build\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
          -o\
          C:\Users\Yasan\Documents\GitHub\AMOLED-mnml-X\app\build\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
          -R\
          @C:\Users\Yasan\Documents\GitHub\AMOLED-mnml-X\app\build\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          C:\Users\Yasan\Documents\GitHub\AMOLED-mnml-X\app\build\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
          --custom-package\
          com.yasang.amoledmnml.xfree\
          -0\
          apk\
          --output-text-symbols\
          C:\Users\Yasan\Documents\GitHub\AMOLED-mnml-X\app\build\intermediates\symbols\debug\R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.0-4818971-windows Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

**Comment by Amitind** [comment]
Just Wanted to let you know
Although I have replaced the app id and key in my  app,
but still few users reported that they got notification ads few days ago.

**Comment by Aksx73** [comment]
> I was testing the library in my desktop with notification ADS. Why are you still using the key provided in the sample project? Please generate a key for your app itself. Sample key is for testing purposes only.
> 
> Edit: I'm basically working on fixing the library and making it compatible with AS 3.2.0 with banner ADS as well. So there will be furthermore testings in future. I suggest you change the key.

Yeah waiting for that.
