### ISSUE TITLE
unable to load a new json file url

### ISSUE THREAD

**Issue by charles935** [sadiqrazasyed/wallpaperboard-enhanced#5]
sir i wanted to add my json url so i deleted your google drive link from string.xml file and added mine then its not loading my contents its showing the old contents.can u plz healp me sir

**Comment by genzcodersz** [comment]
You need to put your link inside "dashboard_configurations.xml" found inside the app module, NOT library.
[This File](https://github.com/sadiqrazasyed/wallpaperboard-enhanced/blob/master/app/src/main/res/values/dashboard_configurations.xml)

Also, if you're using Google Drive link then make sure you change "**open?**" to "**uc?**" in your link.

Example:

> Change
> https://drive.google.com/**open?**id=example
> To
> https://drive.google.com/**uc?**id=example
>

**Comment by charles935** [comment]
thank you so much sir,but it didn't worked tried with both open and uc it shows unable to load new wallpappers

**Comment by genzcodersz** [comment]
Drop me an email with the link to your json file & I'll try to help you with it.

**Comment by Amitind** [comment]
@charles935 
**Try This** Previously I had that problem
Issue is with URL not with app,
App will not work properly with the following URL

```
https://drive.google.com/uc?id=xxxxxxxxxxxxxxxx 
https://github.com/xxxx/xxxx/xxxx.json?raw=true
```
Same JSON file properly works without any error with the following link
`https://raw.githubusercontent.com/xxxxx/xxxxx/xxxxx.json`
you can try firebase also for hosting file.

**Comment by charles935** [comment]
first of all Thank you sir for listening to my issues.
I HAVE SOLVED IT
if anybody is facing similar issues first of all i would recommend you to check library files->jsonstructure all the elements over there should match what you have used in json file of yours
second.
http://myjson.com
use this site to save json files if you have problem in saving with google drive
