### ISSUE TITLE
Is there any json file in the project

### ISSUE THREAD

**Issue by androidxi** [sadiqrazasyed/wallpaperboard-enhanced#6]
Hello sir,
Is there any json files in the project?(not about that google drive link other than that)

Is that google drive file a image folder or a json file ?

**Comment by genzcodersz** [comment]
Hello!

1. There's no json file included inside the project itself, instead a link to it.
2. Google drive link contains a json file from which, the wallpapers are fetched.

Please refer to the [Wiki Site](https://github.com/danimahardhika/wallpaperboard/wiki) to understand better.

Here's an example of the json file structure - [LINK](https://raw.githubusercontent.com/danimahardhika/wallpaperboard/master/json%20example/wallpaper_sample.json)
